package App.utils;

public class View {
    public interface HideOptionalProperties {};
    public interface ShowTitleType{};
    public interface ShowTitle{};
    public interface ShowScientificField{};
    public interface ShowCountry{};
    public interface ShowCity{};
    public interface ShowUniversity{};
    public interface ShowFaculty{};
    public interface ShowAddress{};
    public interface ShowStudyProgram{};
    public interface ShowYearOfStudy{};
    public interface ShowStudentYear{};
    public interface ShowSubject{};
    public interface ShowTopic{};
    public interface ShowTeachingType{};
    public interface ShowTeacherRealization{};
    public interface ShowSubjectRealization{};
    public interface ShowSubjectAttendance{};
    public interface ShowTeacher{};
    public interface ShowStudent{};
    public interface ShowAccountData{};
    public interface ShowAdministrator{};
    public interface ShowAdministrativeStaff{};
    public interface ShowPersonalData{};
    public interface ShowPhone{};
    public interface ShowEmail{};
    public interface ShowUniversityEmails{};
    public interface ShowFacultyEmails{};
    public interface ShowUniversityPhones{};
    public interface ShowFacultyPhones{};
    public interface ShowPrerequisite{};
    public interface ShowTeachingTerm{};
    public interface ShowExamRealization{};
    public interface ShowExam{};
    public interface ShowAuthor{};
    public interface ShowFile{};
    public interface ShowTeachingMaterial{};
    public interface ShowAccountDataPermission{};
    public interface ShowClassroom{};
    public interface ShowPostFile{};
    public interface ShowPost{};
    public interface ShowForumUser{};
    public interface ShowForum{};
    public interface ShowCategory{};
    public interface ShowCategoryRole{};
    public interface ShowForumUserForumRole{};
    public interface ShowForumRole{};
    public interface ShowForumTopic{};
    public interface ShowDissertation{};
    public interface ShowElectiveSubjectAttendance{};
}